### ISSUE TITLE
关于新闻详情页面的问题

### ISSUE THREAD

**Issue by BeatGeneration** [j1406493495/ReadHub#1]
首先感谢你的开源项目，我觉得我从项目中学到了很多。
在这提一个小小的问题，在我的测试机上，我进入每一个新闻详情页面都是这样的

![qq 20180604111549](https://user-images.githubusercontent.com/24977381/40896655-cfec322c-67e8-11e8-874e-5cbd37e0c509.jpg)
![qq 20180604111541](https://user-images.githubusercontent.com/24977381/40896661-d7f9b520-67e8-11e8-8ace-81fd825d3c79.jpg)

看样子感觉像是页面默认滚动到那个位置的

测试手机：华为 荣耀 7i

**Comment by j1406493495** [comment]
可能是虚拟键导致

**Comment by zengjiaozi** [comment]
热门新闻详情页面请求数据失败

**Comment by j1406493495** [comment]
> 热门新闻详情页面请求数据失败
 
readhub后台返回数据格式改了，客户端已修改，重新pull一下。
