### ISSUE TITLE
没有做异常的处理

### ISSUE THREAD

**Issue by songsongtao** [j1406493495/ReadHub#2]
主界面没有做被程序杀死的处理，所有的fragment都是一次性被加载

**Comment by j1406493495** [comment]
主页面只有3个Fragment，所以没有使用FragmentStatePagerAdapter。
主界面没有做被程序杀死的处理，这个是指没有onSaveInstanceState吗？

**Comment by songsongtao** [comment]
对的，貌似也没有懒加载

**Comment by j1406493495** [comment]
页面少，没必要做。3个以上页面的话可以用FragmentStatePagerAdapter。
